### ISSUE TITLE
文章详细页请求  /article/123123.html时会出错

### ISSUE THREAD

**Issue by ivanzhang** [ivanzhang2/haxibiao#8]
https://sentry.io/haxibiao/haxibiaocom/issues/475369777/

```
Symfony\Component\Debug\Exception\FatalErrorException: Uncaught Error: Class 'App\Exceptions\HttpException' not found in /data/www/haxibiao.com/app/Exceptions/Handler.php:54
Stack trace:
#0 /data/www/haxibiao.com/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(112): App\Exceptions\Handler->render(Object(Illuminate\Http\Request), Object(Symfony\Component\Debug\Exception\FatalThrowableError))
#1 /data/www/haxibiao.com/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(89): Illuminate\Foundation\Bootstrap\HandleExceptions->renderHttpResponse(Object(Symfony\Component\Debug\Exception\FatalThrowableError))
#2 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->handleException(Object(Symfony\Component\Debug\Exception\FatalThrowableError))
#3 {main}
  thrown
  File "app/Exceptions/Handler.php", line 54
    $exception = new HttpException(500, 'Whoops!');
```

**Comment by ivanzhang2** [comment]
fixed

**Comment by ivanzhang2** [comment]
xiongdi ,还有问题啊，没好啊
